### PR TITLE
[RFC] Namespace support in knete

### PR DESCRIPTION
**Pull request by planetis-m**
example:

```nim
import std / dom

window.onLoad = proc (e: Event) =
  let svgdiv = document.getElementById("svg1")
  for k in 1 .. 2:
    let svg = buildHtml svg(width = "100", height = "100"):
      circle(cx = "50", cy = "50", r = "40", stroke = "blue",
             stroke-width = "4", fill = "currentColor", class = "icon")
    svgdiv.add(svg)
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="tsvg.js"></script>
  <style>
    .icon {
      color: red
    }
  </style>
</head>
<body>
</head>
<body>
  <div id="svg1"></div>
</body>
</html>
```

### CODE REVIEW

**Comment by planetis-m** [comment]
For it to work, setting the className was replaced with setAttribute("class", x). See also https://github.com/facebook/react/pull/1590

**Comment by planetis-m** [comment]
Problems with it:
- needs an buildNS parentNamespace overload

**Comment by Araq** [comment]
I don't understand this PR. Knete is code duplication and should be refactored. It's also not documented, is it? Do you want to use Knete?

**Comment by planetis-m** [comment]
> I don't understand this PR. Knete is code duplication and should be refactored. It's also not documented, is it? Do you want to use Knete?

I'm trying it yes. My previous attempt https://github.com/pragmagic/karax/pull/179/ to add svg support to karax failed, I tried to work on knete instead, being just a thin dsl on top of the dom.

So my example produces:

```nim
let ns_369098792 = getChildNamespace(Namespace.none, Tag.svg)
let tmp_369098791 = newNode(ns_369098792, Tag.svg)
setAttr(tmp_369098791, "width", "100")
setAttr(tmp_369098791, "height", "100")
let ns_369098799 = getChildNamespace(ns_369098792, Tag.circle)
let tmp_369098798 = newNode(ns_369098799, Tag.circle)
setAttr(tmp_369098798, "cx", "50")
setAttr(tmp_369098798, "cy", "50")
setAttr(tmp_369098798, "r", "40")
setAttr(tmp_369098798, "stroke", "blue")
setAttr(tmp_369098798, "stroke-width", "4")
setAttr(tmp_369098798, "fill", "currentColor")
setAttr(tmp_369098798, "class", "icon")
add(tmp_369098791, tmp_369098798)
```

That makes svg as well as mathml elements render properly.

**Comment by planetis-m** [comment]
I think it would be better to add a buildSvg overload for karax, but I'm waiting for your feedback and suggestions. 

Main problems with that are: [nodeName](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName) doesn't return all uppercase when inside the svg/mathml namespace. Moreover the xml standard is case-sensitive, which breaks `karax.same`

**Comment by geotre** [comment]
Closing this as we added SVG support in #271

**Pull request closed without merging**
