### PR TITLE
Hot reloading example for the To-Do app using Electron

### PR DESCRIPTION
**Pull request by zah**
To test this, do the following:

1) Install tup from http://gittup.org/tup/
2) Build a local copy of Nim from the js-hot-reloading branch
3) Navigate to the todoapp directory
4) Execute "npm install"
5) Launch the project with "npm start"

You should be able to modify style.css or todoapp.nim and see
the changes applied immediately.

### CODE REVIEW

**Comment by Araq** [comment]
Sorry this took so long to review. It's ok, but please introduce a separate ``hotdotoapp`` example in order to avoid cluttering up the existing code. Todoapp is one of our best examples, it shouldn't contain code that distracts from the task.

**Comment by zah** [comment]
I'll rework the example once the new hot-reloading APIs have landed. We'll ship the required browsersync server as a npm package.

**Comment by timotheecour** [comment]
@zah I've found livereload to work well with karax; curious what are pros and cons of browsersync compared to livereload

**Comment by zah** [comment]
BrowserSync is a more feature-rich system. It has some additional capabilities such as synchronizing the scrolling and clicking behavior across all devices that have opened the page (in other words, you can interact with the page in one of your devices and you see the same interaction on all other connected devices).

**Comment by moigagoo** [comment]
@zah Sorry to resurrect an old thread, but is there any chance this will ever get merged? I'm dying to see a working example of hot code reloading with Karax.

**Comment by geotre** [comment]
@zah you mentioned adjusting this example for the new hot-reloading api, are you still able to do that? This would be a great example to have

**Pull request closed without merging**
