### PR TITLE
move setRenderer for ssr to vdom.nim

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by bung87** [comment]
move to bigger patch https://github.com/karaxnim/karax/pull/208

**Comment by Araq** [comment]
What is the goal of this PR? setRenderer does not belong to vdom.nim

**Comment by bung87** [comment]
karax.nim import js target only module, that will cause compile time error, so I move to vdom.nim

**Comment by Araq** [comment]
Can you move it into its own module instead?

**Comment by bung87** [comment]
so user need import extro module, what's the module name ? I have no idea.

**Comment by Araq** [comment]
I just realized that I don't understand the purpose of `setRenderer` so I cannot give you good advice to where it belongs.

**Comment by bung87** [comment]
it renders to  c backend and generate html to a relative path.

**Comment by Araq** [comment]
Then it should be renamed to something else and vdom can contain it.

**Comment by bung87** [comment]
so what it should be named ?

**Comment by Araq** [comment]
```nim

proc renderToFile*(file: string; renderer: proc (): VNode)

```

No command line handling required.

**Comment by geotre** [comment]
@bung87 do you want to implement the proposed name change (and deprecate the old one) or should we close this PR?

**Comment by geotre** [comment]
I'm going to close this for now, but please let me know if you want to reopen it @bung87

**Pull request closed without merging**
